name: interesting
favicon: null
layout_spectrum: 0.6188053986988962
typography_spectrum: 0.43194610183127224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.11815492832101882
  lightness: 0.05353879975154996
  saturation: 0.14703099615871906
  rhythmicContrast: 0.4827477829530835
purpose: []
